### ISSUE TITLE
Copy-button animation repainting every frame

### ISSUE THREAD

**Issue by gustavcorpas** [antonjuulnaber/timewarp#19]
The animation on the copy-button is making a repaint of the DOM every frame. This is expensive because the browser must verify the visibility of all other nodes in the DOM tree.

**Comment by atjn** [comment]
It's cool tho

**Comment by atjn** [comment]
This actually seems to be a bug in Chrome, and work is underway to fix it:
https://bugs.chromium.org/p/chromium/issues/detail?id=1101002

Firefox works just fine ;)

**Comment by atjn** [comment]
Closing, as this has been fixed in Chromium 87 🥳
